package com.example.trabalhosd;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Controller
@RequestMapping(path="/aluno")
public class AlunoController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AlunoService alunoService;

    @GetMapping("/addAluno")
    public String showAddAlunoForm(Model model) {
        model.addAttribute("Aluno", new Aluno());
        return "addAluno";
    }

    @PostMapping(path="/addAluno") // Map ONLY POST Requests
    public String addAluno (@ModelAttribute Aluno aluno) {
        alunoService.save(aluno);
        return "redirect:/aluno/alunos";
    }

    @GetMapping("/alunos")
    public String listarAlunos(Model model) {
        List<Aluno> alunos = alunoService.listAlunos();
        model.addAttribute("alunos", alunos);
        return "alunos";  // Nome do template Thymeleaf sem a extensão .html
    }
}
