package com.example.trabalhosd;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping(path="/demo")
public class AlunoController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AlunoRepository alunoRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (/*@RequestParam String name, @RequestParam String email*/) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Aluno n = new Aluno();
        n.setAno(2);
        n.setIdade(2);
        n.setNome("nome2");
        n.setCurso("curso2");
        n.setMorada("morada2");
        n.setEmail("email2");
        n.setTelefone("telefone2");
        n.setNota(2);
        n.setAno(2);
        alunoRepository.save(n);
        return "Saved";
    }
    @GetMapping(path="/all")
    public @ResponseBody Iterable<Aluno> getAllUsers() {
        // This returns a JSON or XML with the users
        return alunoRepository.findAll();
    }
}
